// Automatically generated by astro-icon
// 49dc50a938b693410b8c5d2a2bb1644eae3a3ac395409a0b7ae6e72f95b979be

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "icon-arrow-right"
		| "icon-tri-down";
}