export const typeSetKeyword = new Map<string, Array<string>>();

typeSetKeyword.set('{TextColor}', [
  "'main'",
  "'sub'",
  "'link'",
  "'linkSub'",
  "'blue'",
  "'blueDarken'",
  "'pink'",
  "'pinkDarken'",
  "'orange'",
  "'orangeDarken'",
  "'purple'",
  "'purpleDarken'",
  "'green'",
  "'greenDarken'",
  "'red'",
  "'redDarken'",
  "'black'",
  "'blackDarken'",
  "'white'",
]);

typeSetKeyword.set('{Spacing}', ["'xxs'", "'xs'", "'sm'", "'md'", "'lg'", "'xl'", "'xxl'"]);

typeSetKeyword.set('{BackgroundColor}', [
  "'blue'",
  "'blueDarken'",
  "'blueInverse'",
  "'blueInverseDarken'",
  "'pink'",
  "'pinkDarken'",
  "'pinkInverse'",
  "'pinkInverseDarken'",
  "'orange'",
  "'orangeDarken'",
  "'orangeInverse'",
  "'orangeInverseDarken'",
  "'purple'",
  "'purpleDarken'",
  "'purpleInverse'",
  "'purpleInverseDarken'",
  "'green'",
  "'greenDarken'",
  "'greenInverse'",
  "'greenInverseDarken'",
  "'red'",
  "'redDarken'",
  "'redInverse'",
  "'redInverseDarken'",
  "'black'",
  "'blackDarken'",
  "'blackInverse'",
  "'blackInverseDarken'",
  "'white'",
]);

typeSetKeyword.set('{Border}', [
  "'blue'",
  "'blueThick'",
  "'blueDarken'",
  "'blueDarkenThick'",
  "'pink'",
  "'pinkThick'",
  "'pinkDarken'",
  "'pinkDarkenThick'",
  "'orange'",
  "'orangeThick'",
  "'orangeDarken'",
  "'orangeDarkenThick'",
  "'purple'",
  "'purpleThick'",
  "'purpleDarken'",
  "'purpleDarkenThick'",
  "'green'",
  "'greenThick'",
  "'greenDarken'",
  "'greenDarkenThick'",
  "'red'",
  "'redThick'",
  "'redDarken'",
  "'redDarkenThick'",
  "'black'",
  "'blackThick'",
  "'blackDarken'",
  "'blackDarkenThick'",
]);

typeSetKeyword.set('{Width}', [
  "'cap'",
  "'ch'",
  "'em'",
  "'ex'",
  "'ic'",
  "'lh'",
  "'rcap'",
  "'rem'",
  "'rex'",
  "'ric'",
  "'rlh'",
  "'vh'",
  "'vmax'",
  "'vmin'",
  "'vw'",
  "'vb'",
  "'vi'",
  "'cqw'",
  "'cqh'",
  "'cqi'",
  "'cqb'",
  "'cqmin'",
  "'cqmax'",
  "'px'",
  "'cm'",
  "'mm'",
  "'q'",
  "'in'",
  "'pc'",
  "'pt'",
  "'%'",
  "'auto'",
  "'fit-content'",
  "'fit-content()'",
  "'min-content'",
  "'max-content'",
  "'var()'",
]);

typeSetKeyword.set('{MaxWidth}', [
  "'cap'",
  "'ch'",
  "'em'",
  "'ex'",
  "'ic'",
  "'lh'",
  "'rcap'",
  "'rem'",
  "'rex'",
  "'ric'",
  "'rlh'",
  "'vh'",
  "'vmax'",
  "'vmin'",
  "'vw'",
  "'vb'",
  "'vi'",
  "'cqw'",
  "'cqh'",
  "'cqi'",
  "'cqb'",
  "'cqmin'",
  "'cqmax'",
  "'px'",
  "'cm'",
  "'mm'",
  "'q'",
  "'in'",
  "'pc'",
  "'pt'",
  "'%'",
  "'none'",
  "'fit-content'",
  "'fit-content()'",
  "'min-content'",
  "'max-content'",
  "'var()'",
]);

typeSetKeyword.set('{MinWidth}', typeSetKeyword.get('{Width}')!);

typeSetKeyword.set('{Radius}', ["'xs'", "'sm'", "'md'", "'lg'"]);

typeSetKeyword.set('{BodyFontSize}', ["'xs'", "'sm'", "'md'", "'lg'"]);

typeSetKeyword.set('{BodyLeading}', ["'default'", "'narrow'"]);
